version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    build:
      context: filebeat/
    volumes:
      - ./app/log:/var/log/apache2
      - ./filebeat/config:/etc/filebeat
    networks:
      - elk
    depends_on:
      - logstash

  app:
    build:
      context: app/
    volumes:
      - ./app/php:/var/www/html
      - ./app/config/vhost.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      - ./app/log:/var/log/apache2
    ports:
      - "80:80"
    networks:
      - elk
    depends_on:
      - logstash

networks:

  elk:
    driver: bridge
